server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true
  instance:
    instance-id: gateway-${server.port}
    prefer-ip-address: true

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:                         # 网关路由配置
      - id: payment                   # 路由id，自定义，只要唯一即可
        uri: lb://PAYMENT-SERVER      # 路由的目标地址 lb就是负载均衡，后面跟服务名称
        predicates:                   # 路由断言，也就是判断请求是否符合路由规则的条件
        - Path=/payment/**            # 这个是按照路径匹配，只要以/payment/开头就符合要求

