server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true
  instance:
    instance-id: consumer-hystrix-order-${server.port}
    prefer-ip-address: true

spring:
  application:
    name: consumer-hystrix-order

# 开启hystrix服务熔断
feign:
  circuitbreaker:
    enabled: true
