server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true
  instance:
    instance-id: consumer-openfeign-order-${server.port}
    prefer-ip-address: true

spring:
  application:
    name: consume-openfeign-order