server:
  port: 8011

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true
  instance:
    instance-id: provider-stream-${server.port}
    prefer-ip-address: true

spring:
  application:
    name: provider-stream

  #消息中间件配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: spring
    password: 123456
  cloud:
    stream:
      bindings:
        output-out-0:
          destination: message